public enum Provincia {
    BUENOSAIRES,CATAMARCA,CHACO,CHUBUT,CORDOBA,CORRIENTES,ENTRERIOS,FORMOSA,JUJUY,LAPAMPA,LARIOJA,MENDOZA,
    NEUQUEN,RIONEGRO,SALTA,SANJUAN,SANLUIS,SANTACRUZ,SANTAFE,SANTIAGODELESTERO,TIERRADELFUEGO,TUCUMAN
}